/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBtn: typeof import('./src/components/AppBtn.vue')['default']
    GlobalNav: typeof import('./src/components/GlobalNav.vue')['default']
    HomeHero: typeof import('./src/sections/HomeHero.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    ShoeCard: typeof import('./src/components/ShoeCard.vue')['default']
  }
}
