/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBtn: typeof import('./components/AppBtn.vue')['default']
    CustomerReviews: typeof import('./sections/CustomerReviews.vue')['default']
    GlobalFooter: typeof import('./sections/GlobalFooter.vue')['default']
    GlobalNav: typeof import('./components/GlobalNav.vue')['default']
    HomeHero: typeof import('./sections/HomeHero.vue')['default']
    OurServices: typeof import('./sections/OurServices.vue')['default']
    PopularProductCard: typeof import('./components/PopularProductCard.vue')['default']
    PopularProducts: typeof import('./sections/PopularProducts.vue')['default']
    ReviewCard: typeof import('./components/ReviewCard.vue')['default']
    ServiceCard: typeof import('./components/ServiceCard.vue')['default']
    Services: typeof import('./sections/Services.vue')['default']
    ShoeCard: typeof import('./components/ShoeCard.vue')['default']
    SpecialOffer: typeof import('./sections/SpecialOffer.vue')['default']
    Subscribe: typeof import('./sections/Subscribe.vue')['default']
    SubscribeUs: typeof import('./sections/SubscribeUs.vue')['default']
    SuperQuality: typeof import('./sections/SuperQuality.vue')['default']
  }
}
