/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBtn: typeof import('./components/AppBtn.vue')['default']
    GlobalNav: typeof import('./components/GlobalNav.vue')['default']
    HomeHero: typeof import('./sections/HomeHero.vue')['default']
    PopularProductCard: typeof import('./components/PopularProductCard.vue')['default']
    PopularProducts: typeof import('./sections/PopularProducts.vue')['default']
    ShoeCard: typeof import('./components/ShoeCard.vue')['default']
  }
}
